[package]
name = "psd_sdk_rs"
version = "0.1.0"
authors = ["corey.fcx <corey.fcx@alibaba-inc.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
cc = "1.0"
